lib/App/TimeTracker/Data/Task.pm

Not a huge thing, but ensures that the keys of the
JSON object are always in the same order. It minimizes
the noise if, for example, you have the ~/.TimeTracker
directory under revision control.

output the JSON in its canonical form

---

lib/App/TimeTracker/Command/Core.pm

Tasks have a Maybe[Str] description. When you add the content to the
table formatting in the list-command, the "description" might not be in
the list, having the filename shifted one column to the left.
This fixes the list output

Fix spacing in lists without description

---

lib/App/TimeTracker.pm

Hello, this is from https://pullrequest.club.
This fixes a link to the `tracker` script in the POD documentation for `App::TimeTracker`. For some reason the `L<tracker>` POD command in `App::TimeTracker` was translated into
https://metacpan.org/pod/distribution/App-TimeTracker/bin/tracker_bash_autocomplete when it should be https://metacpan.org/pod/release/DOMM/App-TimeTracker-3.000/bin/tracker.

Fixes link in POD documentation.

---

bin/tracker_bash_autocomplete
lib/App/TimeTracker.pm

After some [discussion](https://stackoverflow.com/q/58660214/2173773) at stackoverflow.com,  another way to fix the pod link issue was suggested by user @Grinnz. This PR thus reverts the change introduced in commit 20cc7c22fa639f760925611bf51cd3d5e2d666f2 and instead introduces the fix in the file `bin/tracker_bash_autocomplete`.  I am not sure if this will work but I thought I should mention it since it seems like a more correct approach. You probably have to do a release and see if it works, if not you can always revert to the other fix?

Fix pod link version 2.

---

lib/App/TimeTracker/Command/Core.pm
t/Command/core.t

Subsequent calls of `tracker commands` would provide a different order
of the list of commands each time it was called.  This I found to be
confusing and it was difficult to find the command one was looking for.
Alphabetically sorting the list of available commands makes finding a
given command much easier.  I've also added a test for the `commands`
command to ensure the output is as expected.

Sort list of available commands for consistency

---

dist.ini

Dist::Zilla was trying to include vim `.swp` files when building the
dist prior to testing it (e.g. when running `dzil test`) and this was
causing errors such as:
```
Could not decode UTF-8 t/Command/.core.t.swp; filename set by GatherDir
(Dist::Zilla::Plugin::GatherDir line 225); encoded_content added by
GatherDir (Dist::Zilla::Plugin::GatherDir line 226); error was: UTF-8
"\xA8" does not map to Unicode at
/home/cochrane/perl5/perlbrew/perls/perl-5.20.3/lib/site_perl/5.20.3/x86_64-linux/Encode.pm
line 228.
```
By excluding such files from being gathered, one can keep files open in
vim and still run the test suite in another terminal.

Stop gathering vim `.swp` files when building dist

---

lib/App/TimeTracker/Command/Core.pm

Now the indentation matches the surrounding scope, making it easier to
read the code.

Indent incorrectly outdented variable

---

bin/tracker

While reading the docs for the `tracker` program, I noticed a few things that needed correcting.  Mostly these were typos or simply wrapping long lines, however the build and install documentation for a git checkout were no longer correct (it mentioned using `Build.PL` which is only available in the tarball of the distribution).  I've updated this documentation to match how the project is currently built and installed.  I've split these changes into separate commits so that you can cherry pick them as you please.
If you would like anything changed or updated here, please let me know and I'll be happy to update the PR and resubmit :-)

Some tracker docs fixes

---

README.md
dist.ini

There have been commits in 2020 so it's probably a good idea to bump the
copyright year as well.

Bump the copyright year

---

Changes
bin/tracker_bash_autocomplete
t/Command/core.t
t/Task/start.t
t/Task/storage_location.t
t/TimeTracker/find_task_files.t
t/TimeTracker/helpers.t
t/testlib/Fixtures.pm

Some projects consider this a must, and will disallow commits to be submitted which contain trailing whitespace (the Linux kernel is an example project where trailing whitespace isn't permitted).  Other projects see whitespace cleanup as simply nit-picking.  Either way I thought I'd submit this fix just in case it's of interest to you :-)

Purge trailing whitespace in source files

---

t/TimeTracker/find_task_files.t

... because leading zeros are actually octal numbers, so this could have
been a subtle bug if `oct(1)` were different from `int(1)`.

Remove leading zero from integer

---

t/Command/core.t

Previously the `current` command was run without its output being checked for anything.
I think the assertions here are sufficient so as to be useful.  Let me know if you think there's still room for improvement.

Add assertions to test of `current` command

---

lib/App/TimeTracker/Data/Task.pm
t/Command/core.t
t/Task/helpers.t

The implementation always added an extra minute to the output, hence
when a task duration showed 00:15:00, the `rounded_minutes` value came
out at 16.  In the general case a duration of 00:x:00 would have a
`rounded_minutes` value of `x+1`.  The solution implemented here uses
a [hint from PerlMonks](https://www.perlmonks.org/bare/?node_id=257208),
which mentioned that to round to the nearest integer one must use
`sprintf "%.0f" $value` instead of `sprintf "%d" $value` because the
latter has the same truncation behaviour as `int()`.  This commit also
adds tests at the `Data::Task` level but also at the `Command::core`
level (which is where I noticed the discrepancy to start with).

Fix off-by-one rounding error in Task->rounded_minutes

---

lib/App/TimeTracker/Command/Core.pm

... so that the `--help` output is more helpful in understanding the meaning of the options.
I also realigned the fat commas to the now longer `documentation` attribute constructor option.

Document the --from, --to, --this and --last options

---

dist.ini

Both the `Repository` and the `GitHub::Meta` plugins set the
`resources.repository.web` distribution metadata attribute.  This causes
the following error when running e.g. `dzil test` or `dzil build`:
```
Duplication of element resources.repository.web at /path/to/Dist/Zilla.pm line 594.
```
and hence the dist can't be built or tested.  This change gets things to
work again.
What really confuses me about this issue is that it only turned up today
and I've not seen it before and the current configuration has been
present for years and the conflicting modules were last released in
2018, so I honestly don't know how this arose so suddenly.  Looking at
the bugs for the `Repository` plugin, it seems that it doesn't play with
other plugins (such as `MetaResources`) nicely, so it seems like the …

Remove conflicting Repository Dist::Zilla plugin

---

bin/tracker

Since search.cpan.org has been completely replaced by metacpan, the docs don't need to refer to search.cpan.org anymore and all references can point to metacpan instead.

Remove search.cpan.org links

---

bin/tracker
dist.ini

This patch updates the documentation to point users to GitHub issues for bug reports as opposed to RT, which was used before. The `dist.ini` configuration was already pointing to GitHub; the docs needed updating to reflect this.
I also fixed a minor configuration issue also related to handling metadata sourced from GitHub.

Refer to GitHub bugtracker in documentation

---

README.md

It seems that Dist::Zilla wants to translate colons in URIs to their
respective percent-encoding.

Fix URI colons in README

---

bin/tracker
lib/App/TimeTracker/Command/Core.pm

Extend and clarify the meaning and importance of the `init` command to hopefully reduce new user confusion in the future.

Extend init command documentation

---

dist.ini

In order to run `dzil authordeps --missing | cpanm` to completion, it
was necessary to add `OurPkgVersion` to the list of required plugins.
Afterwards, `dzil test` and `dzil listdeps` failed to run due to missing
`license` and `copyright_holder` fields.  These fields have been added
and it is possible to build and test the dist again.
Also, for some reason which I've not yet been able to work out, the version is set to 3.003 automatically in the README. This is definitely incorrect, but I've not been able to find out what's causing that issue.  @domm do you know what could be causing that?
Also, I don't know if this patch is the right way to go about fixing the build issues; it could be that you need to include `OurPkgVersion` into your bundle so that that line is no longer required.  How …

Fix Dist::Zilla build problems

---

perltidyrc
t/00-load.t
t/Command/core.t
t/Command/rt_73859_daychange.t
t/Command/rt_88867_start_help.t
t/Proto/config.t
t/Proto/run.t
t/Task/current.t
t/Task/helpers.t
t/Task/start.t
t/Task/storage_location.t
t/TimeTracker/datetime_coerce.t
t/TimeTracker/find_task_files.t
t/TimeTracker/helpers.t

This patch adds a usable `perltidy` configuration and then uses this configuration to "tidy" the test files.

Tidy test code via perltidy

---

README.md
lib/App/TimeTracker.pm

... which brings the docs up to date with the code, which had set GitHub
as the location for submitting bug reports in commit c0ec0bbf.

Tell users to submit bugs via GitHub
